language: java
jdk:
  - oraclejdk7
  
sudo: required

before_install:
 - chmod +x gradlew
 
script:
  - ./gradlew clean build -i --continue
  
deploy:
  provider: releases
  api_key: ${api_key}
  file: "build/libs/Project.jar"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
