language: java
jdk:
  - oraclejdk7
  
sudo: required

before_install:
 - chmod +x gradlew
 
script:
  - ./gradlew clean build -i --continue
  
deploy:
  provider: releases
  api_key: "ecddac6bad183a188b3287c11b2fb3b23aac08f0"
  file: "build/libs/Project.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

